DELETE FROM events WHERE true;
DELETE FROM workloads WHERE true;
DELETE FROM customers WHERE true;

INSERT INTO customers (label, name_canonical) VALUES ('Acme', 'Acme Corp.');
INSERT INTO workloads (customer_id, title) 
	VALUES (
			(SELECT customer_id FROM customers WHERE label = 'Acme'),
			'Big MySQL migration'
		);
INSERT INTO events (customer_id, workload_id) 
	VALUES (
			(SELECT customer_id FROM customers WHERE label = 'Acme'),
			(SELECT workload_id FROM workloads WHERE title = 'Big MySQL migration')
		);

INSERT INTO customers (label, name_canonical, segment, industry) VALUES 
	('Stellar Solutions', 'Stellar Solutions Inc.', 'SMB', 'Manufacturing'),
	('Envision Consulting', 'Envision Consulting Group', 'Corporate', 'Real Estate'),
	('Summit Ventures', 'Summit Ventures LLC', 'Select', 'Travel and Leisure'),
	('BlueSky Innovations', 'BlueSky Innovations', 'Select', 'Travel and Leisure'),
	('BrightPath Enterprises', 'BrightPath Enterprises', 'Enterprise', 'Manufacturing'),
	('Dynamic Directions', 'Dynamic Directions Inc.', 'Select', 'Media and Entertainment'),
	('Proven Progress', 'Proven Progress LLC', 'Select', 'Travel and Leisure'),
	('Redwood Partners', 'Redwood Partners', 'SMB', 'Manufacturing'),
	('Top Tier', 'Top Tier Technologies', 'SMB', 'Real Estate'),
	('NextWave Industries', 'NextWave Industries', 'Select', 'Manufacturing'),
	('Visionary Ventures', 'Visionary Ventures Inc.', 'Enterprise', 'Financial Services'),
	('Boldly Better', 'Boldly Better Business', 'SMB', 'Media and Entertainment'),
	('Elite Innovations', 'Elite Innovations LLC', 'Corporate', 'Media and Entertainment'),
	('Future Foresight', 'Future Foresight Group', 'SMB', 'Real Estate'),
	('Precision Partners', 'Precision Partners Inc.', 'Select', 'Media and Entertainment'),
	('Stellar Strategies', 'Stellar Strategies', 'Select', 'Financial Services'),
	('Apex Advancement', 'Apex Advancement Group', 'Corporate', 'Media and Entertainment'),
	('Ignite Ideas', 'Ignite Ideas LLC', 'Corporate', 'Manufacturing'),
	('Thrive Consulting', 'Thrive Consulting Co.', 'Select', 'Real Estate'),
	('Fortitude Funding', 'Fortitude Funding Co.', 'Enterprise', 'Manufacturing'),
	('Bluebird Brands', 'Bluebird Brands', 'Select', 'Logistics'),
	('Nimbus Networks', 'Nimbus Networks Inc.', 'Enterprise', 'Travel and Leisure'),
	('Inception Industries', 'Inception Industries', 'SMB', 'Manufacturing'),
	('Titan Technologies', 'Titan Technologies', 'Enterprise', 'Travel and Leisure'),
	('Progress Partners', 'Progress Partners LLC', 'Corporate', 'Manufacturing'),
	('Catalyst Consulting', 'Catalyst Consulting Group', 'Select', 'Real Estate'),
	('Inspired Intelligence', 'Inspired Intelligence Inc.', 'SMB', 'Financial Services'),
	('Phoenix Partnerships', 'Phoenix Partnerships', 'Select', 'Healthcare'),
	('NextGen Innovations', 'NextGen Innovations LLC', 'Corporate', 'Healthcare'),
	('Precision Progress', 'Precision Progress Inc.', 'Select', 'Manufacturing'),
	('Fortitude Frontiers', 'Fortitude Frontiers', 'Enterprise', 'Travel and Leisure'),
	('Nimbus Network', 'Nimbus Network Solutions', 'SMB', 'Healthcare'),
	('Inception Innovations', 'Inception Innovations', 'SMB', 'Media and Entertainment'),
	('Titan Transformation', 'Titan Transformation Co.', 'Corporate', 'Media and Entertainment'),
	('Vertex Ventures', 'Vertex Ventures Group', 'Corporate', 'Travel and Leisure'),
	('Progress Progression', 'Progress Progression Partners', 'Select', 'Travel and Leisure'),
	('Catalystic Concepts', 'Catalystic Concepts Co.', 'Corporate', 'Media and Entertainment'),
	('Inspired Ideals', 'Inspired Ideals LLC', 'Select', 'Financial Services'),
	('Phoenix Performance', 'Phoenix Performance Partners', 'Select', 'Logistics'),
	('Inflection Point', 'Inflection Point Progression', 'Select', 'Travel and Leisure'),
	('Pinnacle Performance', 'Pinnacle Performance Solutions', 'Select', 'Real Estate'),
	('Prime Progression', 'Prime Progression LLC', 'Corporate', 'Media and Entertainment'),
	('Eclipse Enterprises', 'Eclipse Enterprises Group', 'SMB', 'Healthcare'),
	('NextGen Progression', 'NextGen Progression Partners', 'Enterprise', 'Real Estate'),
	('Synergy Solutions', 'Synergy Solutions Consulting', 'SMB', 'Travel and Leisure'),
	('Precision Progression', 'Precision Progression Group', 'Select', 'Healthcare'),
	('Forward Foresight', 'Forward Foresight Ventures', 'Corporate', 'Media and Entertainment'),
	('Fortitude Frontier', 'Fortitude Frontier Enterprises', 'Select', 'Manufacturing'),
	('Redwood Resources', 'Redwood Resources LLC', 'Enterprise', 'Manufacturing'),
	('Future Focus', 'Future Focus Firm LLC', 'Enterprise', 'Financial Services'),
	('Beyond Boundaries', 'Beyond Boundaries Ventures', 'Corporate', 'Media and Entertainment'),
	('Bright Bridge', 'Bright Bridge Consulting Co.', 'Enterprise', 'Financial Services'),
	('Stellar Startups', 'Stellar Startups Group', 'Enterprise', 'Healthcare'),
	('Catalystic Consulting', 'Catalystic Consulting Group', 'Select', 'Logistics'),
	('Envision Endurance', 'Envision Endurance LLC', 'Corporate', 'Healthcare'),
	('Elite Enterprises', 'Elite Enterprises Group', 'Corporate', 'Manufacturing'),
	('Summit Solutions', 'Summit Solutions LLC', 'Enterprise', 'Financial Services'),
	('Dynamic Development', 'Dynamic Development Group', 'SMB', 'Healthcare'),
	('Proven Progression', 'Proven Progression LLC', 'SMB', 'Financial Services'),
	('Bright Beginnings', 'Bright Beginnings Group', 'Select', 'Healthcare'),
	('Quantum Quest', 'Quantum Quest Solutions', 'Select', 'Media and Entertainment'),
	('Ignite Innovation', 'Ignite Innovation LLC', 'Select', 'Financial Services'),
	('Thrive Together', 'Thrive Together LLC', 'Corporate', 'Healthcare'),
	('Horizon Holdings', 'Horizon Holdings Group', 'Corporate', 'Travel and Leisure'),
	('Optimum Outcomes', 'Optimum Outcomes Solutions', 'Select', 'Healthcare'),
	('Fortitude Finance', 'Fortitude Finance Group', 'SMB', 'Logistics'),
	('Bluebird Business', 'Bluebird Business Strategies', 'Enterprise', 'Financial Services'),
	('Silver Summit', 'Silver Summit Group', 'Corporate', 'Healthcare');