DELETE FROM events WHERE true;
DELETE FROM workloads WHERE true;
DELETE FROM customers WHERE true;

INSERT INTO customers (label, name_canonical, segment, industry) VALUES 
('Artisphere', 'Artisphere', 'Corporate', 'Retail'),
('Blendify', 'Blendify', 'Select', 'Retail'),
('FurniChroma', 'FurniChroma', 'SMB', 'Retail'),
('Essence', 'Essence', 'Select', 'Retail'),
('Revela', 'Revela', 'Enterprise', 'Retail'),
('Harbor House', 'HARBOR HOUSE INC.', 'Corporate', 'Retail'),
('Terra Chic', 'TERRA CHIC GMBH', 'Select', 'Retail'),
('Urban Haven', 'Urban Haven', 'Select', 'Retail'),
('Vivida', 'Vivida', 'Enterprise', 'Retail'),
('Moda', 'Moda', 'Corporate', 'Retail'),
('StyleFusion', 'STYLEFUSION LLC', 'Enterprise', 'Retail'),
('Nest Haven', 'Nest Haven', 'Corporate', 'Retail'),
('ChromaHaven', 'ChromaHaven', 'Enterprise', 'Retail'),
('ChromaSphere', 'ChromaSphere', 'Enterprise', 'Retail'),
('Nuvia', 'NUVIA CORPORATION', 'SMB', 'Retail'),
('HarmonyHaus', 'HarmonyHaus', 'SMB', 'Retail'),
('Reviva', 'Reviva', 'Corporate', 'Retail'),
('Harmony Hub', 'HARMONY HUB LLC', 'Corporate', 'Retail'),
('Haven Home', 'Haven Home', 'SMB', 'Retail'),
('Cosmo Style', 'Cosmo Style', 'Corporate', 'Retail'),
('Renovo', 'Renovo', 'Enterprise', 'Retail'),
('Orion', 'Orion', 'Corporate', 'Retail'),
('VerveCraft', 'VerveCraft', 'Enterprise', 'Retail'),
('Craftopia', 'CRAFTOPIA INC.', 'SMB', 'Retail'),
('Fusion', 'Fusion', 'SMB', 'Retail'),
('ModaBlend', 'ModaBlend', 'Select', 'Retail'),
('ZephyrVibe', 'ZephyrVibe', 'Corporate', 'Retail'),
('Verve', 'Verve', 'Enterprise', 'Retail'),
('DesignCraft', 'DESIGNCRAFT CORPORATION', 'Corporate', 'Retail'),
('StyleForge', 'StyleForge', 'SMB', 'Retail'),
('Luminous Living', 'Luminous Living', 'Enterprise', 'Retail'),
('OrionHaus', 'ORIONHAUS CORPORATION', 'SMB', 'Retail'),
('DecoPro', 'DecoPro', 'Corporate', 'Retail'),
('Harmonize', 'Harmonize', 'Enterprise', 'Retail'),
('FurniVibe', 'FurniVibe', 'SMB', 'Retail'),
('FurniBlend', 'FurniBlend', 'Enterprise', 'Retail'),
('DecoNest', 'DecoNest', 'SMB', 'Retail'),
('Vividverse', 'Vividverse', 'Select', 'Retail'),
('FurniCore', 'FurniCore', 'SMB', 'Retail'),
('Vividaire', 'Vividaire', 'Corporate', 'Retail'),
('Craftique', 'CRAFTIQUE GMBH', 'SMB', 'Retail'),
('Serenity Space', 'SERENITY SPACE CORPORATION', 'Select', 'Retail'),
('Vivara', 'Vivara', 'Enterprise', 'Retail'),
('VividHome', 'VividHome', 'Enterprise', 'Retail'),
('Blendbook', 'Blendbook', 'Select', 'Retail'),
('Nuvolo', 'Nuvolo', 'Corporate', 'Retail'),
('Nestopia', 'Nestopia', 'Select', 'Retail'),
('Vibrant Vibe', 'Vibrant Vibe', 'Select', 'Retail'),
('Mixora', 'Mixora', 'Corporate', 'Retail'),
('Renovite', 'Renovite', 'Corporate', 'Retail'),
('Luxe', 'LUXE GMBH', 'Select', 'Retail'),
('ChromaCraft', 'CHROMACRAFT INC.', 'Corporate', 'Retail'),
('TechnoGaming', 'TechnoGaming', 'Select', 'Gaming'),
('Zephyr', 'ZEPHYR INC.', 'Enterprise', 'Gaming'),
('NovaGen', 'NovaGen', 'Enterprise', 'Gaming'),
('Vixen', 'Vixen', 'Corporate', 'Gaming'),
('Vortexia', 'Vortexia', 'Corporate', 'Gaming'),
('Odyssey', 'ODYSSEY GMBH', 'Corporate', 'Gaming'),
('TechnoArt', 'TECHNOART INC.', 'SMB', 'Gaming'),
('TechnoDraw', 'TECHNODRAW GMBH', 'Corporate', 'Gaming'),
('EnigmaSphere', 'EnigmaSphere', 'Corporate', 'Gaming'),
('Celestial', 'CELESTIAL CORPORATION', 'Corporate', 'Gaming'),
('PixelCraft', 'PixelCraft', 'Enterprise', 'Gaming'),
('LunarScape', 'LunarScape', 'Enterprise', 'Gaming'),
('Pixel', 'Pixel', 'Select', 'Gaming'),
('Catalyst', 'Catalyst', 'Select', 'Gaming'),
('Synapse', 'Synapse', 'Corporate', 'Gaming'),
('Luminary', 'Luminary', 'Select', 'Gaming'),
('GameScape', 'GAMESCAPE CORPORATION', 'Corporate', 'Gaming'),
('SpectraTech', 'SpectraTech', 'Enterprise', 'Gaming'),
('Artix', 'ARTIX INC.', 'SMB', 'Gaming'),
('CyberLink', 'CyberLink', 'Select', 'Gaming'),
('Drawvana', 'Drawvana', 'Select', 'Gaming'),
('DreamForge', 'DreamForge', 'SMB', 'Gaming'),
('Imaginex', 'Imaginex', 'Corporate', 'Gaming'),
('SynthetiX', 'SynthetiX', 'Corporate', 'Gaming'),
('Creativox', 'CREATIVOX GMBH', 'Enterprise', 'Gaming'),
('Arcadia', 'Arcadia', 'Corporate', 'Gaming'),
('Artistry', 'Artistry', 'Corporate', 'Gaming'),
('PulsePoint', 'PULSEPOINT GMBH', 'SMB', 'Gaming'),
('QuantumShift', 'QUANTUMSHIFT INC.', 'SMB', 'Gaming'),
('GameZen', 'GameZen', 'Select', 'Gaming'),
('ElectraWave', 'ElectraWave', 'Corporate', 'Gaming'),
('CreatiX', 'CreatiX', 'Corporate', 'Gaming'),
('ChromaBlend', 'ChromaBlend', 'Enterprise', 'Gaming'),
('Imagix', 'Imagix', 'SMB', 'Gaming'),
('StellarEdge', 'StellarEdge', 'Corporate', 'Gaming'),
('Infinity', 'Infinity', 'Select', 'Gaming'),
('ArtiTech', 'ArtiTech', 'SMB', 'Gaming'),
('Zenith', 'ZENITH CORPORATION', 'Corporate', 'Gaming'),
('EterniTech', 'EterniTech', 'Select', 'Gaming'),
('VividNova', 'VividNova', 'SMB', 'Gaming'),
('Zenithia', 'Zenithia', 'Select', 'Gaming'),
('NebulaLink', 'NebulaLink', 'Corporate', 'Gaming'),
('TechnoSphere', 'TechnoSphere', 'SMB', 'Gaming'),
('Mirage', 'Mirage', 'SMB', 'Gaming'),
('Lumina', 'Lumina', 'Select', 'Gaming'),
('FusionPoint', 'FusionPoint', 'SMB', 'Gaming'),
('Kinetix', 'Kinetix', 'Select', 'Gaming'),
('PixelVortex', 'PixelVortex', 'Enterprise', 'Gaming'),
('Spectrum', 'SPECTRUM INC.', 'Enterprise', 'Gaming'),
('SmartFin', 'SMARTFIN GMBH', 'SMB', 'FinServ'),
('MoneyMakers', 'MoneyMakers', 'Enterprise', 'FinServ'),
('MintMark', 'MINTMARK INC.', 'SMB', 'FinServ'),
('BlendBank', 'BlendBank', 'SMB', 'FinServ'),
('CashCore', 'CashCore', 'Corporate', 'FinServ'),
('PayPulse', 'PayPulse', 'SMB', 'FinServ'),
('Prospera', 'Prospera', 'Enterprise', 'FinServ'),
('Pinnacle', 'Pinnacle', 'Select', 'FinServ'),
('PayZen', 'PAYZEN GMBH', 'Enterprise', 'FinServ'),
('TradeStreet', 'TradeStreet', 'SMB', 'FinServ'),
('EquiLink', 'EQUILINK INC.', 'Enterprise', 'FinServ'),
('Coinify', 'COINIFY LLC', 'Corporate', 'FinServ'),
('CrediMax', 'CREDIMAX GMBH', 'Select', 'FinServ'),
('Fintech', 'Fintech', 'Enterprise', 'FinServ'),
('Investify', 'Investify', 'Corporate', 'FinServ'),
('Credex', 'Credex', 'Select', 'FinServ'),
('FinBlend', 'FinBlend', 'SMB', 'FinServ'),
('Capital', 'CAPITAL GMBH', 'Corporate', 'FinServ'),
('PayPlex', 'PAYPLEX INC.', 'SMB', 'FinServ'),
('Fintrigue', 'Fintrigue', 'SMB', 'FinServ'),
('CashCrest', 'CashCrest', 'Enterprise', 'FinServ'),
('Elevate', 'ELEVATE CORPORATION', 'Enterprise', 'FinServ'),
('PayZenith', 'PAYZENITH INC.', 'Corporate', 'FinServ'),
('FundFlow', 'FUNDFLOW GMBH', 'SMB', 'FinServ'),
('Coinnect', 'COINNECT CORPORATION', 'Corporate', 'FinServ'),
('WealthWise', 'WealthWise', 'Select', 'FinServ'),
('MoneyMint', 'MoneyMint', 'Corporate', 'FinServ'),
('SmartFinex', 'SmartFinex', 'Select', 'FinServ'),
('ProfitPrime', 'ProfitPrime', 'SMB', 'FinServ'),
('WealthStax', 'WealthStax', 'SMB', 'FinServ'),
('ProfitPulse', 'ProfitPulse', 'Enterprise', 'FinServ'),
('Venture', 'VENTURE GMBH', 'Corporate', 'FinServ'),
('CashCove', 'CashCove', 'Enterprise', 'FinServ'),
('CashCraze', 'CashCraze', 'Select', 'FinServ'),
('FundFusion', 'FundFusion', 'Enterprise', 'FinServ'),
('WealthCraft', 'WealthCraft', 'SMB', 'FinServ'),
('SageSense', 'SageSense', 'Enterprise', 'FinServ'),
('WealthWay', 'WealthWay', 'Enterprise', 'FinServ')
;

INSERT INTO workloads (customer_id, title) VALUES
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), 'Lockpay'), 
((SELECT customer_id FROM customers WHERE label = 'Prospera'), 'Payluxe'), 
((SELECT customer_id FROM customers WHERE label = 'FundFusion'), 'Payex'), 
((SELECT customer_id FROM customers WHERE label = 'Artisphere'), 'Payzen'), 
((SELECT customer_id FROM customers WHERE label = 'Vivara'), 'Payplus'), 
((SELECT customer_id FROM customers WHERE label = 'VividNova'), 'Payhaven'), 
((SELECT customer_id FROM customers WHERE label = 'Imaginex'), 'Safepay'), 
((SELECT customer_id FROM customers WHERE label = 'Creativox'), 'Payify'), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), 'Paydefend'), 
((SELECT customer_id FROM customers WHERE label = 'Capital'), 'Payluxe'), 
((SELECT customer_id FROM customers WHERE label = 'Odyssey'), 'Shield'), 
((SELECT customer_id FROM customers WHERE label = 'Artistry'), 'Paybright'), 
((SELECT customer_id FROM customers WHERE label = 'Credex'), 'Payshield'), 
((SELECT customer_id FROM customers WHERE label = 'FurniCore'), 'Payorama'), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), 'Payblend'), 
((SELECT customer_id FROM customers WHERE label = 'Artistry'), 'Payzenith'), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), 'Payfortress'), 
((SELECT customer_id FROM customers WHERE label = 'Drawvana'), 'Trustpay'), 
((SELECT customer_id FROM customers WHERE label = 'WealthCraft'), 'Payguard'), 
((SELECT customer_id FROM customers WHERE label = 'SmartFin'), 'Paypro'), 
((SELECT customer_id FROM customers WHERE label = 'ProfitPrime'), 'Trustwave'), 
((SELECT customer_id FROM customers WHERE label = 'ArtiTech'), 'Payfort'), 
((SELECT customer_id FROM customers WHERE label = 'Craftopia'), 'Payex'), 
((SELECT customer_id FROM customers WHERE label = 'Vividaire'), 'Payverse'), 
((SELECT customer_id FROM customers WHERE label = 'Craftopia'), 'Paywave'), 
((SELECT customer_id FROM customers WHERE label = 'CashCrest'), 'Paywall'), 
((SELECT customer_id FROM customers WHERE label = 'ChromaHaven'), 'Payblend'), 
((SELECT customer_id FROM customers WHERE label = 'NovaGen'), 'Payflex'), 
((SELECT customer_id FROM customers WHERE label = 'StellarEdge'), 'Payfinity'), 
((SELECT customer_id FROM customers WHERE label = 'Cosmo Style'), 'Paygrid'), 
((SELECT customer_id FROM customers WHERE label = 'Vivida'), 'Vault'), 
((SELECT customer_id FROM customers WHERE label = 'Coinnect'), 'Paywise'), 
((SELECT customer_id FROM customers WHERE label = 'SageSense'), 'Payorama'), 
((SELECT customer_id FROM customers WHERE label = 'PayPulse'), 'Surepay'), 
((SELECT customer_id FROM customers WHERE label = 'ProfitPulse'), 'Payora'), 
((SELECT customer_id FROM customers WHERE label = 'CashCove'), 'Paylink'), 
((SELECT customer_id FROM customers WHERE label = 'Haven Home'), 'Paypass'), 
((SELECT customer_id FROM customers WHERE label = 'Zenithia'), 'Payflex'), 
((SELECT customer_id FROM customers WHERE label = 'Blendify'), 'Trustpay'), 
((SELECT customer_id FROM customers WHERE label = 'GameScape'), 'Paycore'), 
((SELECT customer_id FROM customers WHERE label = 'Nest Haven'), 'Payfinity'), 
((SELECT customer_id FROM customers WHERE label = 'WealthCraft'), 'Seccash'), 
((SELECT customer_id FROM customers WHERE label = 'Mirage'), 'Safeguard'), 
((SELECT customer_id FROM customers WHERE label = 'GameZen'), 'Paynect'), 
((SELECT customer_id FROM customers WHERE label = 'Kinetix'), 'Payfusion'), 
((SELECT customer_id FROM customers WHERE label = 'Luxe'), 'SupplyCraft'), 
((SELECT customer_id FROM customers WHERE label = 'FurniCore'), 'TradeQuest'), 
((SELECT customer_id FROM customers WHERE label = 'Mirage'), 'StriveStock'), 
((SELECT customer_id FROM customers WHERE label = 'Pinnacle'), 'TradeSync'), 
((SELECT customer_id FROM customers WHERE label = 'Vixen'), 'StockSphere'), 
((SELECT customer_id FROM customers WHERE label = 'Synapse'), 'SwiftStock'), 
((SELECT customer_id FROM customers WHERE label = 'Spectrum'), 'InvenConnect'), 
((SELECT customer_id FROM customers WHERE label = 'Artix'), 'StockEase'), 
((SELECT customer_id FROM customers WHERE label = 'FurniChroma'), 'StockSphere'), 
((SELECT customer_id FROM customers WHERE label = 'Kinetix'), 'ManageMint'), 
((SELECT customer_id FROM customers WHERE label = 'GameZen'), 'Stockify'), 
((SELECT customer_id FROM customers WHERE label = 'VerveCraft'), 'OptiFlow'), 
((SELECT customer_id FROM customers WHERE label = 'StyleForge'), 'TradeWave'), 
((SELECT customer_id FROM customers WHERE label = 'Nuvia'), 'TradeFlow'), 
((SELECT customer_id FROM customers WHERE label = 'Urban Haven'), 'SynchroSupply'), 
((SELECT customer_id FROM customers WHERE label = 'Nest Haven'), 'Supplyly'), 
((SELECT customer_id FROM customers WHERE label = 'VerveCraft'), 'SupplySense'), 
((SELECT customer_id FROM customers WHERE label = 'Zenith'), 'OptiStock'), 
((SELECT customer_id FROM customers WHERE label = 'Infinity'), 'OptiStock'), 
((SELECT customer_id FROM customers WHERE label = 'SynthetiX'), 'OptiManage'), 
((SELECT customer_id FROM customers WHERE label = 'ZephyrVibe'), 'StockPro'), 
((SELECT customer_id FROM customers WHERE label = 'Imaginex'), 'StockPulse'), 
((SELECT customer_id FROM customers WHERE label = 'Haven Home'), 'SupplyLink'), 
((SELECT customer_id FROM customers WHERE label = 'ChromaCraft'), 'TradeQuest'), 
((SELECT customer_id FROM customers WHERE label = 'Haven Home'), 'StockSense'), 
((SELECT customer_id FROM customers WHERE label = 'TechnoDraw'), 'StockGenie'), 
((SELECT customer_id FROM customers WHERE label = 'FundFlow'), 'TradeSphere'), 
((SELECT customer_id FROM customers WHERE label = 'NovaGen'), 'StockCraft'), 
((SELECT customer_id FROM customers WHERE label = 'ProfitPrime'), 'StockGenius'), 
((SELECT customer_id FROM customers WHERE label = 'ChromaBlend'), 'OptiFlow'), 
((SELECT customer_id FROM customers WHERE label = 'Investify'), 'OptiTrade'), 
((SELECT customer_id FROM customers WHERE label = 'DecoPro'), 'QuikStock'), 
((SELECT customer_id FROM customers WHERE label = 'Nestopia'), 'StockNet'), 
((SELECT customer_id FROM customers WHERE label = 'PayPlex'), 'TradeLink'), 
((SELECT customer_id FROM customers WHERE label = 'Nuvolo'), 'StockWise'), 
((SELECT customer_id FROM customers WHERE label = 'PayPulse'), 'Serendipity'), 
((SELECT customer_id FROM customers WHERE label = 'TechnoArt'), 'Vortex'), 
((SELECT customer_id FROM customers WHERE label = 'Fintrigue'), 'Playmuse'), 
((SELECT customer_id FROM customers WHERE label = 'Vibrant Vibe'), 'Lumina'), 
((SELECT customer_id FROM customers WHERE label = 'Odyssey'), 'Wonderplay'), 
((SELECT customer_id FROM customers WHERE label = 'Cosmo Style'), 'Zephyr'), 
((SELECT customer_id FROM customers WHERE label = 'Mixora'), 'Mindplay'), 
((SELECT customer_id FROM customers WHERE label = 'Zephyr'), 'Gamecraze'), 
((SELECT customer_id FROM customers WHERE label = 'Odyssey'), 'Playmystique'), 
((SELECT customer_id FROM customers WHERE label = 'Venture'), 'Wonderquest'), 
((SELECT customer_id FROM customers WHERE label = 'Fintrigue'), 'Zentopia'), 
((SELECT customer_id FROM customers WHERE label = 'Vivida'), 'Mindrealm'), 
((SELECT customer_id FROM customers WHERE label = 'Blendbook'), 'Nexus'), 
((SELECT customer_id FROM customers WHERE label = 'Coinnect'), 'Quicksilver'), 
((SELECT customer_id FROM customers WHERE label = 'Artistry'), 'Chromaluxe'), 
((SELECT customer_id FROM customers WHERE label = 'Verve'), 'Playnova'), 
((SELECT customer_id FROM customers WHERE label = 'ProfitPrime'), 'Ludora'), 
((SELECT customer_id FROM customers WHERE label = 'GameZen'), 'Playfinity'), 
((SELECT customer_id FROM customers WHERE label = 'Odyssey'), 'Mystique'), 
((SELECT customer_id FROM customers WHERE label = 'Vortexia'), 'Whirlwind'), 
((SELECT customer_id FROM customers WHERE label = 'CrediMax'), 'Pixelite'), 
((SELECT customer_id FROM customers WHERE label = 'VerveCraft'), 'Playzen'), 
((SELECT customer_id FROM customers WHERE label = 'TechnoGaming'), 'Mindspark'), 
((SELECT customer_id FROM customers WHERE label = 'ArtiTech'), 'Questify'), 
((SELECT customer_id FROM customers WHERE label = 'Vividaire'), 'Synapse'), 
((SELECT customer_id FROM customers WHERE label = 'Credex'), 'Spectron'), 
((SELECT customer_id FROM customers WHERE label = 'Fusion'), 'Playluxe'), 
((SELECT customer_id FROM customers WHERE label = 'Coinnect'), 'Playvortex'), 
((SELECT customer_id FROM customers WHERE label = 'Prospera'), 'Playbliss'), 
((SELECT customer_id FROM customers WHERE label = 'CyberLink'), 'Playquark'), 
((SELECT customer_id FROM customers WHERE label = 'LunarScape'), 'Fusion'), 
((SELECT customer_id FROM customers WHERE label = 'WealthCraft'), 'Joyzone'), 
((SELECT customer_id FROM customers WHERE label = 'LunarScape'), 'Gametopia'), 
((SELECT customer_id FROM customers WHERE label = 'Pinnacle'), 'Mindmuse'), 
((SELECT customer_id FROM customers WHERE label = 'Arcadia'), 'Momentum'), 
((SELECT customer_id FROM customers WHERE label = 'Coinify'), 'Playflux'), 
((SELECT customer_id FROM customers WHERE label = 'Mirage'), 'Wonderflux')
;


INSERT INTO events (customer_id, workload_id, timestamp) VALUES
((SELECT customer_id FROM customers WHERE label = 'LunarScape'), (SELECT workload_id FROM workloads WHERE title = 'Gametopia' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'LunarScape')), '2023-09-01 04:43:10.514'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'FundFusion'), (SELECT workload_id FROM workloads WHERE title = 'Payex' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'FundFusion')), '2023-07-29 01:12:56.503'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vortexia'), (SELECT workload_id FROM workloads WHERE title = 'Whirlwind' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vortexia')), '2023-07-11 17:02:51.243'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Artix'), (SELECT workload_id FROM workloads WHERE title = 'StockEase' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Artix')), '2023-07-03 12:08:01.933'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'NovaGen'), (SELECT workload_id FROM workloads WHERE title = 'Payflex' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'NovaGen')), '2023-10-12 02:22:21.899'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Catalyst'), (SELECT workload_id FROM workloads WHERE title = 'InvenSync' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Catalyst')), '2023-12-09 05:51:15.758'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Spectrum'), (SELECT workload_id FROM workloads WHERE title = 'InvenSoft' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Spectrum')), '2023-11-04 22:17:29.418'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Craftopia'), (SELECT workload_id FROM workloads WHERE title = 'Payex' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Craftopia')), '2023-09-01 20:47:24.940'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vivida'), (SELECT workload_id FROM workloads WHERE title = 'Vault' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vivida')), '2023-10-27 12:14:33.515'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Pinnacle'), (SELECT workload_id FROM workloads WHERE title = 'TradeSync' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Pinnacle')), '2023-12-20 18:06:35.886'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Cosmo Style'), (SELECT workload_id FROM workloads WHERE title = 'Paygrid' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Cosmo Style')), '2023-09-14 17:01:30.769'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'FurniBlend'), (SELECT workload_id FROM workloads WHERE title = 'Gamezen' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'FurniBlend')), '2023-10-27 13:39:41.676'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SpectraTech'), (SELECT workload_id FROM workloads WHERE title = 'InvenLink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SpectraTech')), '2023-10-03 06:08:15.960'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Odyssey'), (SELECT workload_id FROM workloads WHERE title = 'Mystique' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Odyssey')), '2023-12-01 23:08:02.133'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'TechnoArt'), (SELECT workload_id FROM workloads WHERE title = 'Vortex' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'TechnoArt')), '2023-08-21 05:01:18.951'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SynthetiX'), (SELECT workload_id FROM workloads WHERE title = 'OptiManage' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SynthetiX')), '2023-08-31 12:42:01.459'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'PayPlex'), (SELECT workload_id FROM workloads WHERE title = 'TradeLink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'PayPlex')), '2023-12-15 20:02:17.443'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Nestopia'), (SELECT workload_id FROM workloads WHERE title = 'StockNet' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Nestopia')), '2023-07-12 23:56:48.706'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Coinnect'), (SELECT workload_id FROM workloads WHERE title = 'Paywise' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Coinnect')), '2023-08-25 21:28:16.740'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'VerveCraft'), (SELECT workload_id FROM workloads WHERE title = 'OptiFlow' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'VerveCraft')), '2023-09-01 19:56:06.609'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Artisphere'), (SELECT workload_id FROM workloads WHERE title = 'Payzen' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Artisphere')), '2023-09-08 01:13:13.986'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), (SELECT workload_id FROM workloads WHERE title = 'Lockpay' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividverse')), '2023-08-30 12:12:22.990'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Credex'), (SELECT workload_id FROM workloads WHERE title = 'Payshield' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Credex')), '2023-12-03 19:43:33.207'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SmartFin'), (SELECT workload_id FROM workloads WHERE title = 'Paypro' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SmartFin')), '2023-11-26 04:16:57.577'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Drawvana'), (SELECT workload_id FROM workloads WHERE title = 'Cashshield' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Drawvana')), '2023-12-24 22:16:29.456'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vivida'), (SELECT workload_id FROM workloads WHERE title = 'Vault' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vivida')), '2023-12-23 16:11:56.185'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vortexia'), (SELECT workload_id FROM workloads WHERE title = 'Whirlwind' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vortexia')), '2023-08-30 22:47:09.819'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Mixora'), (SELECT workload_id FROM workloads WHERE title = 'Mindplay' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Mixora')), '2023-09-19 05:41:05.185'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Zephyr'), (SELECT workload_id FROM workloads WHERE title = 'InvenWise' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Zephyr')), '2023-12-22 10:37:05.824'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SmartFin'), (SELECT workload_id FROM workloads WHERE title = 'Paypro' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SmartFin')), '2023-09-21 06:13:51.818'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'ProfitPrime'), (SELECT workload_id FROM workloads WHERE title = 'Ludora' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'ProfitPrime')), '2023-12-18 22:34:53.347'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'ZephyrVibe'), (SELECT workload_id FROM workloads WHERE title = 'StockPro' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'ZephyrVibe')), '2023-08-05 22:19:22.880'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Haven Home'), (SELECT workload_id FROM workloads WHERE title = 'SupplyLink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Haven Home')), '2023-07-16 22:16:13.008'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'FurniChroma'), (SELECT workload_id FROM workloads WHERE title = 'FlexiStock' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'FurniChroma')), '2023-09-24 06:00:18.825'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividaire'), (SELECT workload_id FROM workloads WHERE title = 'Payverse' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividaire')), '2023-10-27 16:45:55.158'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Artix'), (SELECT workload_id FROM workloads WHERE title = 'StockEase' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Artix')), '2023-10-22 09:34:24.265'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vortexia'), (SELECT workload_id FROM workloads WHERE title = 'Whirlwind' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vortexia')), '2023-09-06 05:48:22.792'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Luxe'), (SELECT workload_id FROM workloads WHERE title = 'SupplyCraft' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Luxe')), '2023-08-10 03:58:00.661'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Venture'), (SELECT workload_id FROM workloads WHERE title = 'Wonderquest' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Venture')), '2023-10-06 12:23:35.974'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividaire'), (SELECT workload_id FROM workloads WHERE title = 'Payverse' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividaire')), '2023-07-27 19:16:05.173'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Haven Home'), (SELECT workload_id FROM workloads WHERE title = 'Paypass' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Haven Home')), '2023-07-16 20:33:58.161'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Capital'), (SELECT workload_id FROM workloads WHERE title = 'Payluxe' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Capital')), '2023-11-17 13:01:14.897'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'CashCrest'), (SELECT workload_id FROM workloads WHERE title = 'Blissful' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'CashCrest')), '2023-11-11 06:31:01.072'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Artix'), (SELECT workload_id FROM workloads WHERE title = 'StockEase' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Artix')), '2023-09-26 12:44:14.639'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividaire'), (SELECT workload_id FROM workloads WHERE title = 'Synapse' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividaire')), '2023-10-26 00:20:56.312'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Fusion'), (SELECT workload_id FROM workloads WHERE title = 'Chromazone' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Fusion')), '2023-07-25 10:24:59.598'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'MoneyMint'), (SELECT workload_id FROM workloads WHERE title = 'InvenBlend' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'MoneyMint')), '2023-08-10 11:22:22.951'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'GameZen'), (SELECT workload_id FROM workloads WHERE title = 'Playfinity' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'GameZen')), '2023-07-08 15:00:45.895'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'NovaGen'), (SELECT workload_id FROM workloads WHERE title = 'StockCraft' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'NovaGen')), '2023-08-12 21:58:51.448'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Fusion'), (SELECT workload_id FROM workloads WHERE title = 'Chromazone' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Fusion')), '2023-12-15 22:00:43.095'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SpectraTech'), (SELECT workload_id FROM workloads WHERE title = 'InvenLink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SpectraTech')), '2023-12-28 06:30:47.587'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Haven Home'), (SELECT workload_id FROM workloads WHERE title = 'Paypass' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Haven Home')), '2023-10-24 08:28:35.650'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'GameZen'), (SELECT workload_id FROM workloads WHERE title = 'Stockify' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'GameZen')), '2023-10-03 15:18:05.422'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'TechnoArt'), (SELECT workload_id FROM workloads WHERE title = 'Vortex' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'TechnoArt')), '2023-10-11 16:31:41.965'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Craftopia'), (SELECT workload_id FROM workloads WHERE title = 'Paywave' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Craftopia')), '2023-08-09 15:52:05.522'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SmartFin'), (SELECT workload_id FROM workloads WHERE title = 'Paypro' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SmartFin')), '2023-07-04 20:09:00.999'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Kinetix'), (SELECT workload_id FROM workloads WHERE title = 'ManageMint' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Kinetix')), '2023-10-10 01:16:00.533'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Artistry'), (SELECT workload_id FROM workloads WHERE title = 'Payzenith' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Artistry')), '2023-08-06 17:49:08.991'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Zenithia'), (SELECT workload_id FROM workloads WHERE title = 'Payflex' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Zenithia')), '2023-11-12 04:24:05.944'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Investify'), (SELECT workload_id FROM workloads WHERE title = 'OptiTrade' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Investify')), '2023-08-31 13:43:15.321'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'DecoNest'), (SELECT workload_id FROM workloads WHERE title = 'Enigmaria' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'DecoNest')), '2023-08-15 12:01:39.548'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Zephyr'), (SELECT workload_id FROM workloads WHERE title = 'InvenWise' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Zephyr')), '2023-12-27 22:34:38.135'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'PulsePoint'), (SELECT workload_id FROM workloads WHERE title = 'Bytebliss' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'PulsePoint')), '2023-08-11 06:39:45.213'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Nuvia'), (SELECT workload_id FROM workloads WHERE title = 'TradeFlow' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Nuvia')), '2023-12-26 07:18:36.031'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), (SELECT workload_id FROM workloads WHERE title = 'Paydefend' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividverse')), '2023-07-30 06:59:40.747'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'LunarScape'), (SELECT workload_id FROM workloads WHERE title = 'Gametopia' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'LunarScape')), '2023-11-27 23:18:53.398'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Nuvia'), (SELECT workload_id FROM workloads WHERE title = 'TradeFlow' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Nuvia')), '2023-10-07 06:12:05.644'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'PayPulse'), (SELECT workload_id FROM workloads WHERE title = 'Surepay' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'PayPulse')), '2023-07-22 12:53:46.364'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Urban Haven'), (SELECT workload_id FROM workloads WHERE title = 'SynchroSupply' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Urban Haven')), '2023-09-20 08:03:31.007'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'ArtiTech'), (SELECT workload_id FROM workloads WHERE title = 'Questify' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'ArtiTech')), '2023-12-06 17:51:18.263'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SmartFin'), (SELECT workload_id FROM workloads WHERE title = 'Paypro' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SmartFin')), '2023-10-16 12:28:27.769'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'CyberLink'), (SELECT workload_id FROM workloads WHERE title = 'Playquark' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'CyberLink')), '2023-10-06 05:12:31.705'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'HarmonyHaus'), (SELECT workload_id FROM workloads WHERE title = 'Fortify' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'HarmonyHaus')), '2023-11-13 07:17:34.439'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'SpectraTech'), (SELECT workload_id FROM workloads WHERE title = 'InvenLink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'SpectraTech')), '2023-09-18 16:58:49.764'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Zenithia'), (SELECT workload_id FROM workloads WHERE title = 'Cashguard' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Zenithia')), '2023-07-03 02:30:35.310'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'GameZen'), (SELECT workload_id FROM workloads WHERE title = 'Playfinity' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'GameZen')), '2023-12-11 16:48:58.750'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Mirage'), (SELECT workload_id FROM workloads WHERE title = 'Safeguard' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Mirage')), '2023-10-08 15:37:03.309'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'GameZen'), (SELECT workload_id FROM workloads WHERE title = 'Paynect' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'GameZen')), '2023-11-20 21:17:26.946'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'EterniTech'), (SELECT workload_id FROM workloads WHERE title = 'Chromatica' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'EterniTech')), '2023-07-18 04:16:35.758'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Fintrigue'), (SELECT workload_id FROM workloads WHERE title = 'Playmuse' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Fintrigue')), '2023-10-09 06:02:22.147'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Credex'), (SELECT workload_id FROM workloads WHERE title = 'Enigma' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Credex')), '2023-08-31 17:03:52.207'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Artisphere'), (SELECT workload_id FROM workloads WHERE title = 'Gameverse' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Artisphere')), '2023-12-25 14:43:38.204'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Craftopia'), (SELECT workload_id FROM workloads WHERE title = 'Paywave' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Craftopia')), '2023-10-16 05:20:29.891'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Artistry'), (SELECT workload_id FROM workloads WHERE title = 'Paybright' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Artistry')), '2023-11-18 11:13:30.020'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'VerveCraft'), (SELECT workload_id FROM workloads WHERE title = 'Playzen' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'VerveCraft')), '2023-08-04 18:26:09.113'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Arcadia'), (SELECT workload_id FROM workloads WHERE title = 'Momentum' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Arcadia')), '2023-07-23 23:37:41.254'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vivida'), (SELECT workload_id FROM workloads WHERE title = 'Vault' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vivida')), '2023-09-03 22:03:50.419'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'PayPlex'), (SELECT workload_id FROM workloads WHERE title = 'TradeLink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'PayPlex')), '2023-07-08 00:49:21.492'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'FurniCore'), (SELECT workload_id FROM workloads WHERE title = 'TradeQuest' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'FurniCore')), '2023-12-04 14:18:28.444'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Cosmo Style'), (SELECT workload_id FROM workloads WHERE title = 'Zephyr' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Cosmo Style')), '2023-12-21 00:35:10.345'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), (SELECT workload_id FROM workloads WHERE title = 'Payfortress' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividverse')), '2023-12-03 17:13:51.791'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'CashCove'), (SELECT workload_id FROM workloads WHERE title = 'Paylink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'CashCove')), '2023-07-28 01:36:49.284'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), (SELECT workload_id FROM workloads WHERE title = 'Payblend' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividverse')), '2023-10-28 10:29:04.743'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Fusion'), (SELECT workload_id FROM workloads WHERE title = 'Playluxe' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Fusion')), '2023-09-16 07:47:03.339'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'TechnoDraw'), (SELECT workload_id FROM workloads WHERE title = 'StockGenie' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'TechnoDraw')), '2023-11-19 23:41:36.129'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Prospera'), (SELECT workload_id FROM workloads WHERE title = 'Playbliss' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Prospera')), '2023-09-06 01:20:46.925'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Fusion'), (SELECT workload_id FROM workloads WHERE title = 'Playluxe' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Fusion')), '2023-08-04 17:09:57.840'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Spectrum'), (SELECT workload_id FROM workloads WHERE title = 'InvenSoft' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Spectrum')), '2023-08-28 14:53:33.151'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Craftopia'), (SELECT workload_id FROM workloads WHERE title = 'Paywave' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Craftopia')), '2023-09-11 10:12:59.208'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividaire'), (SELECT workload_id FROM workloads WHERE title = 'Synapse' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividaire')), '2023-07-24 00:56:20.818'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Fusion'), (SELECT workload_id FROM workloads WHERE title = 'Chromazone' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Fusion')), '2023-08-21 00:14:51.747'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Fintrigue'), (SELECT workload_id FROM workloads WHERE title = 'Zentopia' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Fintrigue')), '2023-08-06 08:00:57.551'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'FurniCore'), (SELECT workload_id FROM workloads WHERE title = 'TradeQuest' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'FurniCore')), '2023-09-15 01:25:12.895'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Vividverse'), (SELECT workload_id FROM workloads WHERE title = 'Payfortress' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Vividverse')), '2023-07-16 03:19:07.040'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'ProfitPulse'), (SELECT workload_id FROM workloads WHERE title = 'Payora' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'ProfitPulse')), '2023-11-08 21:19:45.161'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Mirage'), (SELECT workload_id FROM workloads WHERE title = 'StriveStock' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Mirage')), '2023-08-29 12:35:19.797'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Renovite'), (SELECT workload_id FROM workloads WHERE title = 'InvenLink' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Renovite')), '2023-08-15 16:20:06.183'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'Credex'), (SELECT workload_id FROM workloads WHERE title = 'Payshield' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'Credex')), '2023-09-04 22:52:01.243'::timestamptz), 
((SELECT customer_id FROM customers WHERE label = 'ChromaHaven'), (SELECT workload_id FROM workloads WHERE title = 'Payblend' AND customer_id = (SELECT customer_id FROM customers WHERE label = 'ChromaHaven')), '2023-08-21 04:09:37.849'::timestamptz)
;