version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - psql-data:/tmp/dev/pgsql/data
    env_file:
        - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  psql-data: